# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ja:
  languageCode: ja-jp
  contentDir: content
  title: "Ishikawa Lab."
  weight: 1

en:
  languageCode: en-us
  contentDir: content/en
  title: "Ishikawa Lab. [en]"
  weight: 2
